/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AgendaDeEntregasRouteImport } from './routes/agenda-de-entregas'
import { Route as AssinaturasRouteImport } from './routes/assinaturas'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as CentroDeCustosRouteImport } from './routes/centro-de-custos'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as CobrancasRouteImport } from './routes/cobrancas'
import { Route as ComercialRouteImport } from './routes/comercial'
import { Route as ConciliacaoRouteImport } from './routes/conciliacao'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ContasAPagarRouteImport } from './routes/contas-a-pagar'
import { Route as ContasAReceberRouteImport } from './routes/contas-a-receber'
import { Route as ContratosRouteImport } from './routes/contratos'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as CustomerSuccessRouteImport } from './routes/customer-success'
import { Route as DesenvolvimentoRouteImport } from './routes/desenvolvimento'
import { Route as DocumentosRouteImport } from './routes/documentos'
import { Route as DreRouteImport } from './routes/dre'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as FiscalRouteImport } from './routes/fiscal'
import { Route as FluxoDeCaixaRouteImport } from './routes/fluxo-de-caixa'
import { Route as FornecedoresRouteImport } from './routes/fornecedores'
import { Route as IaFinanceiraRouteImport } from './routes/ia-financeira'
import { Route as IndicadoresRouteImport } from './routes/indicadores'
import { Route as IntegracoesRouteImport } from './routes/integracoes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as NotificacoesRouteImport } from './routes/notificacoes'
import { Route as PermissoesRouteImport } from './routes/permissoes'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as RhRouteImport } from './routes/rh'
import { Route as SuporteRouteImport } from './routes/suporte'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as CentroDeCustosCentroIdRouteImport } from './routes/centro-de-custos_.$centroId'
import { Route as ClientesClienteIdRouteImport } from './routes/clientes/$clienteId'
import { Route as ContratosContratoIdRouteImport } from './routes/contratos_.$contratoId'
import { Route as EstoqueSplatRouteImport } from './routes/estoque.$'
import { Route as ProjetosProjetoIdRouteImport } from './routes/projetos/$projetoId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaDeEntregasRoute = AgendaDeEntregasRouteImport.update({
  id: '/agenda-de-entregas',
  path: '/agenda-de-entregas',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinaturasRoute = AssinaturasRouteImport.update({
  id: '/assinaturas',
  path: '/assinaturas',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const CentroDeCustosRoute = CentroDeCustosRouteImport.update({
  id: '/centro-de-custos',
  path: '/centro-de-custos',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const CobrancasRoute = CobrancasRouteImport.update({
  id: '/cobrancas',
  path: '/cobrancas',
  getParentRoute: () => rootRouteImport,
} as any)
const ComercialRoute = ComercialRouteImport.update({
  id: '/comercial',
  path: '/comercial',
  getParentRoute: () => rootRouteImport,
} as any)
const ConciliacaoRoute = ConciliacaoRouteImport.update({
  id: '/conciliacao',
  path: '/conciliacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContasAPagarRoute = ContasAPagarRouteImport.update({
  id: '/contas-a-pagar',
  path: '/contas-a-pagar',
  getParentRoute: () => rootRouteImport,
} as any)
const ContasAReceberRoute = ContasAReceberRouteImport.update({
  id: '/contas-a-receber',
  path: '/contas-a-receber',
  getParentRoute: () => rootRouteImport,
} as any)
const ContratosRoute = ContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerSuccessRoute = CustomerSuccessRouteImport.update({
  id: '/customer-success',
  path: '/customer-success',
  getParentRoute: () => rootRouteImport,
} as any)
const DesenvolvimentoRoute = DesenvolvimentoRouteImport.update({
  id: '/desenvolvimento',
  path: '/desenvolvimento',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosRoute = DocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const DreRoute = DreRouteImport.update({
  id: '/dre',
  path: '/dre',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const FiscalRoute = FiscalRouteImport.update({
  id: '/fiscal',
  path: '/fiscal',
  getParentRoute: () => rootRouteImport,
} as any)
const FluxoDeCaixaRoute = FluxoDeCaixaRouteImport.update({
  id: '/fluxo-de-caixa',
  path: '/fluxo-de-caixa',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedoresRoute = FornecedoresRouteImport.update({
  id: '/fornecedores',
  path: '/fornecedores',
  getParentRoute: () => rootRouteImport,
} as any)
const IaFinanceiraRoute = IaFinanceiraRouteImport.update({
  id: '/ia-financeira',
  path: '/ia-financeira',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicadoresRoute = IndicadoresRouteImport.update({
  id: '/indicadores',
  path: '/indicadores',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegracoesRoute = IntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacoesRoute = NotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissoesRoute = PermissoesRouteImport.update({
  id: '/permissoes',
  path: '/permissoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const RhRoute = RhRouteImport.update({
  id: '/rh',
  path: '/rh',
  getParentRoute: () => rootRouteImport,
} as any)
const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const CentroDeCustosCentroIdRoute = CentroDeCustosCentroIdRouteImport.update({
  id: '/centro-de-custos_/$centroId',
  path: '/centro-de-custos/$centroId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesClienteIdRoute = ClientesClienteIdRouteImport.update({
  id: '/$clienteId',
  path: '/$clienteId',
  getParentRoute: () => ClientesRoute,
} as any)
const ContratosContratoIdRoute = ContratosContratoIdRouteImport.update({
  id: '/contratos_/$contratoId',
  path: '/contratos/$contratoId',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueSplatRoute = EstoqueSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => EstoqueRoute,
} as any)
const ProjetosProjetoIdRoute = ProjetosProjetoIdRouteImport.update({
  id: '/$projetoId',
  path: '/$projetoId',
  getParentRoute: () => ProjetosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/agenda-de-entregas': typeof AgendaDeEntregasRoute
  '/assinaturas': typeof AssinaturasRoute
  '/categorias': typeof CategoriasRoute
  '/centro-de-custos': typeof CentroDeCustosRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/cobrancas': typeof CobrancasRoute
  '/comercial': typeof ComercialRoute
  '/conciliacao': typeof ConciliacaoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contas-a-pagar': typeof ContasAPagarRoute
  '/contas-a-receber': typeof ContasAReceberRoute
  '/contratos': typeof ContratosRoute
  '/crm': typeof CrmRoute
  '/customer-success': typeof CustomerSuccessRoute
  '/desenvolvimento': typeof DesenvolvimentoRoute
  '/documentos': typeof DocumentosRoute
  '/dre': typeof DreRoute
  '/estoque': typeof EstoqueRouteWithChildren
  '/fiscal': typeof FiscalRoute
  '/fluxo-de-caixa': typeof FluxoDeCaixaRoute
  '/fornecedores': typeof FornecedoresRoute
  '/ia-financeira': typeof IaFinanceiraRoute
  '/indicadores': typeof IndicadoresRoute
  '/integracoes': typeof IntegracoesRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/marketing': typeof MarketingRoute
  '/notificacoes': typeof NotificacoesRoute
  '/permissoes': typeof PermissoesRoute
  '/produtos': typeof ProdutosRoute
  '/projetos': typeof ProjetosRouteWithChildren
  '/relatorios': typeof RelatoriosRoute
  '/rh': typeof RhRoute
  '/suporte': typeof SuporteRoute
  '/usuarios': typeof UsuariosRoute
  '/centro-de-custos/$centroId': typeof CentroDeCustosCentroIdRoute
  '/clientes/$clienteId': typeof ClientesClienteIdRoute
  '/contratos/$contratoId': typeof ContratosContratoIdRoute
  '/estoque/$': typeof EstoqueSplatRoute
  '/projetos/$projetoId': typeof ProjetosProjetoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/agenda-de-entregas': typeof AgendaDeEntregasRoute
  '/assinaturas': typeof AssinaturasRoute
  '/categorias': typeof CategoriasRoute
  '/centro-de-custos': typeof CentroDeCustosRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/cobrancas': typeof CobrancasRoute
  '/comercial': typeof ComercialRoute
  '/conciliacao': typeof ConciliacaoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contas-a-pagar': typeof ContasAPagarRoute
  '/contas-a-receber': typeof ContasAReceberRoute
  '/contratos': typeof ContratosRoute
  '/crm': typeof CrmRoute
  '/customer-success': typeof CustomerSuccessRoute
  '/desenvolvimento': typeof DesenvolvimentoRoute
  '/documentos': typeof DocumentosRoute
  '/dre': typeof DreRoute
  '/estoque': typeof EstoqueRouteWithChildren
  '/fiscal': typeof FiscalRoute
  '/fluxo-de-caixa': typeof FluxoDeCaixaRoute
  '/fornecedores': typeof FornecedoresRoute
  '/ia-financeira': typeof IaFinanceiraRoute
  '/indicadores': typeof IndicadoresRoute
  '/integracoes': typeof IntegracoesRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/marketing': typeof MarketingRoute
  '/notificacoes': typeof NotificacoesRoute
  '/permissoes': typeof PermissoesRoute
  '/produtos': typeof ProdutosRoute
  '/projetos': typeof ProjetosRouteWithChildren
  '/relatorios': typeof RelatoriosRoute
  '/rh': typeof RhRoute
  '/suporte': typeof SuporteRoute
  '/usuarios': typeof UsuariosRoute
  '/centro-de-custos/$centroId': typeof CentroDeCustosCentroIdRoute
  '/clientes/$clienteId': typeof ClientesClienteIdRoute
  '/contratos/$contratoId': typeof ContratosContratoIdRoute
  '/estoque/$': typeof EstoqueSplatRoute
  '/projetos/$projetoId': typeof ProjetosProjetoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/agenda-de-entregas': typeof AgendaDeEntregasRoute
  '/assinaturas': typeof AssinaturasRoute
  '/categorias': typeof CategoriasRoute
  '/centro-de-custos': typeof CentroDeCustosRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/cobrancas': typeof CobrancasRoute
  '/comercial': typeof ComercialRoute
  '/conciliacao': typeof ConciliacaoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contas-a-pagar': typeof ContasAPagarRoute
  '/contas-a-receber': typeof ContasAReceberRoute
  '/contratos': typeof ContratosRoute
  '/crm': typeof CrmRoute
  '/customer-success': typeof CustomerSuccessRoute
  '/desenvolvimento': typeof DesenvolvimentoRoute
  '/documentos': typeof DocumentosRoute
  '/dre': typeof DreRoute
  '/estoque': typeof EstoqueRouteWithChildren
  '/fiscal': typeof FiscalRoute
  '/fluxo-de-caixa': typeof FluxoDeCaixaRoute
  '/fornecedores': typeof FornecedoresRoute
  '/ia-financeira': typeof IaFinanceiraRoute
  '/indicadores': typeof IndicadoresRoute
  '/integracoes': typeof IntegracoesRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/marketing': typeof MarketingRoute
  '/notificacoes': typeof NotificacoesRoute
  '/permissoes': typeof PermissoesRoute
  '/produtos': typeof ProdutosRoute
  '/projetos': typeof ProjetosRouteWithChildren
  '/relatorios': typeof RelatoriosRoute
  '/rh': typeof RhRoute
  '/suporte': typeof SuporteRoute
  '/usuarios': typeof UsuariosRoute
  '/centro-de-custos_/$centroId': typeof CentroDeCustosCentroIdRoute
  '/clientes/$clienteId': typeof ClientesClienteIdRoute
  '/contratos_/$contratoId': typeof ContratosContratoIdRoute
  '/estoque/$': typeof EstoqueSplatRoute
  '/projetos/$projetoId': typeof ProjetosProjetoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/agenda-de-entregas'
    | '/assinaturas'
    | '/categorias'
    | '/centro-de-custos'
    | '/clientes'
    | '/cobrancas'
    | '/comercial'
    | '/conciliacao'
    | '/configuracoes'
    | '/contas-a-pagar'
    | '/contas-a-receber'
    | '/contratos'
    | '/crm'
    | '/customer-success'
    | '/desenvolvimento'
    | '/documentos'
    | '/dre'
    | '/estoque'
    | '/fiscal'
    | '/fluxo-de-caixa'
    | '/fornecedores'
    | '/ia-financeira'
    | '/indicadores'
    | '/integracoes'
    | '/login'
    | '/logs'
    | '/marketing'
    | '/notificacoes'
    | '/permissoes'
    | '/produtos'
    | '/projetos'
    | '/relatorios'
    | '/rh'
    | '/suporte'
    | '/usuarios'
    | '/centro-de-custos/$centroId'
    | '/clientes/$clienteId'
    | '/contratos/$contratoId'
    | '/estoque/$'
    | '/projetos/$projetoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/agenda-de-entregas'
    | '/assinaturas'
    | '/categorias'
    | '/centro-de-custos'
    | '/clientes'
    | '/cobrancas'
    | '/comercial'
    | '/conciliacao'
    | '/configuracoes'
    | '/contas-a-pagar'
    | '/contas-a-receber'
    | '/contratos'
    | '/crm'
    | '/customer-success'
    | '/desenvolvimento'
    | '/documentos'
    | '/dre'
    | '/estoque'
    | '/fiscal'
    | '/fluxo-de-caixa'
    | '/fornecedores'
    | '/ia-financeira'
    | '/indicadores'
    | '/integracoes'
    | '/login'
    | '/logs'
    | '/marketing'
    | '/notificacoes'
    | '/permissoes'
    | '/produtos'
    | '/projetos'
    | '/relatorios'
    | '/rh'
    | '/suporte'
    | '/usuarios'
    | '/centro-de-custos/$centroId'
    | '/clientes/$clienteId'
    | '/contratos/$contratoId'
    | '/estoque/$'
    | '/projetos/$projetoId'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/agenda-de-entregas'
    | '/assinaturas'
    | '/categorias'
    | '/centro-de-custos'
    | '/clientes'
    | '/cobrancas'
    | '/comercial'
    | '/conciliacao'
    | '/configuracoes'
    | '/contas-a-pagar'
    | '/contas-a-receber'
    | '/contratos'
    | '/crm'
    | '/customer-success'
    | '/desenvolvimento'
    | '/documentos'
    | '/dre'
    | '/estoque'
    | '/fiscal'
    | '/fluxo-de-caixa'
    | '/fornecedores'
    | '/ia-financeira'
    | '/indicadores'
    | '/integracoes'
    | '/login'
    | '/logs'
    | '/marketing'
    | '/notificacoes'
    | '/permissoes'
    | '/produtos'
    | '/projetos'
    | '/relatorios'
    | '/rh'
    | '/suporte'
    | '/usuarios'
    | '/centro-de-custos_/$centroId'
    | '/clientes/$clienteId'
    | '/contratos_/$contratoId'
    | '/estoque/$'
    | '/projetos/$projetoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AgendaDeEntregasRoute: typeof AgendaDeEntregasRoute
  AssinaturasRoute: typeof AssinaturasRoute
  CategoriasRoute: typeof CategoriasRoute
  CentroDeCustosRoute: typeof CentroDeCustosRoute
  ClientesRoute: typeof ClientesRouteWithChildren
  CobrancasRoute: typeof CobrancasRoute
  ComercialRoute: typeof ComercialRoute
  ConciliacaoRoute: typeof ConciliacaoRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ContasAPagarRoute: typeof ContasAPagarRoute
  ContasAReceberRoute: typeof ContasAReceberRoute
  ContratosRoute: typeof ContratosRoute
  CrmRoute: typeof CrmRoute
  CustomerSuccessRoute: typeof CustomerSuccessRoute
  DesenvolvimentoRoute: typeof DesenvolvimentoRoute
  DocumentosRoute: typeof DocumentosRoute
  DreRoute: typeof DreRoute
  EstoqueRoute: typeof EstoqueRouteWithChildren
  FiscalRoute: typeof FiscalRoute
  FluxoDeCaixaRoute: typeof FluxoDeCaixaRoute
  FornecedoresRoute: typeof FornecedoresRoute
  IaFinanceiraRoute: typeof IaFinanceiraRoute
  IndicadoresRoute: typeof IndicadoresRoute
  IntegracoesRoute: typeof IntegracoesRoute
  LoginRoute: typeof LoginRoute
  LogsRoute: typeof LogsRoute
  MarketingRoute: typeof MarketingRoute
  NotificacoesRoute: typeof NotificacoesRoute
  PermissoesRoute: typeof PermissoesRoute
  ProdutosRoute: typeof ProdutosRoute
  ProjetosRoute: typeof ProjetosRouteWithChildren
  RelatoriosRoute: typeof RelatoriosRoute
  RhRoute: typeof RhRoute
  SuporteRoute: typeof SuporteRoute
  UsuariosRoute: typeof UsuariosRoute
  CentroDeCustosCentroIdRoute: typeof CentroDeCustosCentroIdRoute
  ContratosContratoIdRoute: typeof ContratosContratoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda-de-entregas': {
      id: '/agenda-de-entregas'
      path: '/agenda-de-entregas'
      fullPath: '/agenda-de-entregas'
      preLoaderRoute: typeof AgendaDeEntregasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinaturas': {
      id: '/assinaturas'
      path: '/assinaturas'
      fullPath: '/assinaturas'
      preLoaderRoute: typeof AssinaturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/centro-de-custos': {
      id: '/centro-de-custos'
      path: '/centro-de-custos'
      fullPath: '/centro-de-custos'
      preLoaderRoute: typeof CentroDeCustosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cobrancas': {
      id: '/cobrancas'
      path: '/cobrancas'
      fullPath: '/cobrancas'
      preLoaderRoute: typeof CobrancasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercial': {
      id: '/comercial'
      path: '/comercial'
      fullPath: '/comercial'
      preLoaderRoute: typeof ComercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conciliacao': {
      id: '/conciliacao'
      path: '/conciliacao'
      fullPath: '/conciliacao'
      preLoaderRoute: typeof ConciliacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contas-a-pagar': {
      id: '/contas-a-pagar'
      path: '/contas-a-pagar'
      fullPath: '/contas-a-pagar'
      preLoaderRoute: typeof ContasAPagarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contas-a-receber': {
      id: '/contas-a-receber'
      path: '/contas-a-receber'
      fullPath: '/contas-a-receber'
      preLoaderRoute: typeof ContasAReceberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contratos': {
      id: '/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof ContratosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-success': {
      id: '/customer-success'
      path: '/customer-success'
      fullPath: '/customer-success'
      preLoaderRoute: typeof CustomerSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desenvolvimento': {
      id: '/desenvolvimento'
      path: '/desenvolvimento'
      fullPath: '/desenvolvimento'
      preLoaderRoute: typeof DesenvolvimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos': {
      id: '/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof DocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dre': {
      id: '/dre'
      path: '/dre'
      fullPath: '/dre'
      preLoaderRoute: typeof DreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fiscal': {
      id: '/fiscal'
      path: '/fiscal'
      fullPath: '/fiscal'
      preLoaderRoute: typeof FiscalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fluxo-de-caixa': {
      id: '/fluxo-de-caixa'
      path: '/fluxo-de-caixa'
      fullPath: '/fluxo-de-caixa'
      preLoaderRoute: typeof FluxoDeCaixaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedores': {
      id: '/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof FornecedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ia-financeira': {
      id: '/ia-financeira'
      path: '/ia-financeira'
      fullPath: '/ia-financeira'
      preLoaderRoute: typeof IaFinanceiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicadores': {
      id: '/indicadores'
      path: '/indicadores'
      fullPath: '/indicadores'
      preLoaderRoute: typeof IndicadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integracoes': {
      id: '/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof IntegracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificacoes': {
      id: '/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof NotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissoes': {
      id: '/permissoes'
      path: '/permissoes'
      fullPath: '/permissoes'
      preLoaderRoute: typeof PermissoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rh': {
      id: '/rh'
      path: '/rh'
      fullPath: '/rh'
      preLoaderRoute: typeof RhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/centro-de-custos_/$centroId': {
      id: '/centro-de-custos_/$centroId'
      path: '/centro-de-custos/$centroId'
      fullPath: '/centro-de-custos/$centroId'
      preLoaderRoute: typeof CentroDeCustosCentroIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/$clienteId': {
      id: '/clientes/$clienteId'
      path: '/$clienteId'
      fullPath: '/clientes/$clienteId'
      preLoaderRoute: typeof ClientesClienteIdRouteImport
      parentRoute: typeof ClientesRoute
    }
    '/contratos_/$contratoId': {
      id: '/contratos_/$contratoId'
      path: '/contratos/$contratoId'
      fullPath: '/contratos/$contratoId'
      preLoaderRoute: typeof ContratosContratoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque/$': {
      id: '/estoque/$'
      path: '/$'
      fullPath: '/estoque/$'
      preLoaderRoute: typeof EstoqueSplatRouteImport
      parentRoute: typeof EstoqueRoute
    }
    '/projetos/$projetoId': {
      id: '/projetos/$projetoId'
      path: '/$projetoId'
      fullPath: '/projetos/$projetoId'
      preLoaderRoute: typeof ProjetosProjetoIdRouteImport
      parentRoute: typeof ProjetosRoute
    }
  }
}

interface ClientesRouteChildren {
  ClientesClienteIdRoute: typeof ClientesClienteIdRoute
}

const ClientesRouteChildren: ClientesRouteChildren = {
  ClientesClienteIdRoute: ClientesClienteIdRoute,
}

const ClientesRouteWithChildren = ClientesRoute._addFileChildren(
  ClientesRouteChildren,
)

interface EstoqueRouteChildren {
  EstoqueSplatRoute: typeof EstoqueSplatRoute
}

const EstoqueRouteChildren: EstoqueRouteChildren = {
  EstoqueSplatRoute: EstoqueSplatRoute,
}

const EstoqueRouteWithChildren =
  EstoqueRoute._addFileChildren(EstoqueRouteChildren)

interface ProjetosRouteChildren {
  ProjetosProjetoIdRoute: typeof ProjetosProjetoIdRoute
}

const ProjetosRouteChildren: ProjetosRouteChildren = {
  ProjetosProjetoIdRoute: ProjetosProjetoIdRoute,
}

const ProjetosRouteWithChildren = ProjetosRoute._addFileChildren(
  ProjetosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AgendaDeEntregasRoute: AgendaDeEntregasRoute,
  AssinaturasRoute: AssinaturasRoute,
  CategoriasRoute: CategoriasRoute,
  CentroDeCustosRoute: CentroDeCustosRoute,
  ClientesRoute: ClientesRouteWithChildren,
  CobrancasRoute: CobrancasRoute,
  ComercialRoute: ComercialRoute,
  ConciliacaoRoute: ConciliacaoRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ContasAPagarRoute: ContasAPagarRoute,
  ContasAReceberRoute: ContasAReceberRoute,
  ContratosRoute: ContratosRoute,
  CrmRoute: CrmRoute,
  CustomerSuccessRoute: CustomerSuccessRoute,
  DesenvolvimentoRoute: DesenvolvimentoRoute,
  DocumentosRoute: DocumentosRoute,
  DreRoute: DreRoute,
  EstoqueRoute: EstoqueRouteWithChildren,
  FiscalRoute: FiscalRoute,
  FluxoDeCaixaRoute: FluxoDeCaixaRoute,
  FornecedoresRoute: FornecedoresRoute,
  IaFinanceiraRoute: IaFinanceiraRoute,
  IndicadoresRoute: IndicadoresRoute,
  IntegracoesRoute: IntegracoesRoute,
  LoginRoute: LoginRoute,
  LogsRoute: LogsRoute,
  MarketingRoute: MarketingRoute,
  NotificacoesRoute: NotificacoesRoute,
  PermissoesRoute: PermissoesRoute,
  ProdutosRoute: ProdutosRoute,
  ProjetosRoute: ProjetosRouteWithChildren,
  RelatoriosRoute: RelatoriosRoute,
  RhRoute: RhRoute,
  SuporteRoute: SuporteRoute,
  UsuariosRoute: UsuariosRoute,
  CentroDeCustosCentroIdRoute: CentroDeCustosCentroIdRoute,
  ContratosContratoIdRoute: ContratosContratoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
